# ReadTheDocs Configuration
# https://docs.readthedocs.io/en/stable/config-file/v2/

version: 2

# Build configuration
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  version: "3.10"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Documentation source directory
docs:
  source: docs
  builder: html

# Build commands
formats:
  - pdf
  - epub

# Use custom domain
domains:
  - docs.aiplatform.io

# Search index language
search:
  ignore:
    - "/404"
    - "/search"

# Notification settings
notifications:
  slack:
    enabled: false

# Preview mode
preview:
  enabled: true

# VCS settings
vcs:
  backend: github
